# Generated by Django 5.2 on 2025-04-04 23:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(choices=[('healthcare', 'Healthcare'), ('finance', 'Finance'), ('tech', 'Technology'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('education', 'Education'), ('hospitality', 'Hospitality'), ('other', 'Other')], default='healthcare', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DepartmentShiftSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_swap_policy', models.CharField(choices=[('automatic', 'Automatic'), ('review', 'Review')], default='review', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shift_settings', to='scheduling.department')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('original_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_from', to='scheduling.shift')),
                ('requested_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_to', to='scheduling.shift')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_swap_requests', to='core.worker')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_swap_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
