# Generated by Django 5.1.7 on 2025-03-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_department_organization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="organisation",
            new_name="organization",
        ),
    ]
