# Generated by Django 5.2 on 2025-04-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_role', to='core.customrole'),
        ),
    ]
