# Generated by Django 5.2 on 2025-04-09 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_custom_role'),
        ('scheduling', '0002_organization_created_at_organization_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='scheduling.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='customrole',
            unique_together={('name', 'organization')},
        ),
    ]
