# Generated by Django 5.2 on 2025-04-05 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0022_alter_billmodel_bill_items_and_more'),
        ('spending_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spending_expenses', to='django_ledger.journalentrymodel'),
        ),
    ]
