# Generated by Django 5.2 on 2025-04-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('benefit_type', models.CharField(choices=[('insurance', 'Insurance'), ('savings', 'Savings Account'), ('investment', 'Investment Plan'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('default_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('enrollment_start', models.DateField(blank=True, null=True)),
                ('enrollment_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='scheduling.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('breakdown', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.worker')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_deductions', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='core.worker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_period', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='payroll_benefits.benefit')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_benefits', to='core.worker')),
            ],
            options={
                'unique_together': {('worker', 'benefit', 'deduction_period')},
            },
        ),
    ]
