# Generated by Django 5.2 on 2025-04-05 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0022_alter_billmodel_bill_items_and_more'),
        ('scheduling', '0002_organization_created_at_organization_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntity',
            fields=[
                ('entitymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_ledger.entitymodel')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entity', to='scheduling.organization')),
            ],
            options={
                'verbose_name': 'Accounting Entity',
                'verbose_name_plural': 'Accounting Entities',
            },
            bases=('django_ledger.entitymodel',),
        ),
        migrations.CreateModel(
            name='ReportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_day', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_settings', to='accounting.accountingentity')),
            ],
        ),
    ]
